APP = figlet
SRCS = figlet.c crc.c getopt.c
CFLAGS += -Wno-implicit-function-declaration -Wno-deprecated-non-prototype \
	-Wno-unused-variable -Wno-unused-but-set-variable

include ../../mlibc_app.mk
