#
# @file : /src/boot/limine.conf
# @brief : Limine boot configuration file.
#  
# This file is a part of the Zen (ZenOS)
# Operating System, and is released under
# the terms of the MIT Licensing : Read
# LICENSE at the root of the repository.
# 
# @copyright (c) 2026
# @author : Rishies2010
#

timeout: 3
interface_branding: ZenOS
interface_help_hidden: true
interface_branding_color: 5

/Boot
    protocol: limine
    comment: Boot ZenOS
    path: boot():/boot/kernel.bin
    resolution: 1920x1080x32
